// layout.server.tsx (for metadata)
import type { Metadata } from 'next';

// Metadata for the app
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ServerLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
